language: node_js
node_js:
- '4.3.2'
- '6.9.0'
script:
- if [[ "$TRAVIS_NODE_VERSION" == "6.9.0" ]]; then mocha ./tests/lib && npm test; fi
- if [[ "$TRAVIS_NODE_VERSION" == "4.3.2" ]]; then npm test; fi
